name: Publish ngx-cookie-service to NPM
on:
  push:
    ### Publish on new tag release
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Print tag
        run: ${{ env.TAG }}
